/Users/beggers/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:34: NotOpenSSLWarning: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Traceback (most recent call last):
  File "/Users/beggers/code/chroma/starter-project/chat.py", line 50, in <module>
    main()
  File "/Users/beggers/code/chroma/starter-project/chat.py", line 14, in main
    insert_docs(c, docs)
  File "/Users/beggers/code/chroma/starter-project/chat.py", line 38, in insert_docs
    c.add(doc_list, metadatas=[{"source": "me" for d in doc_list}], ids=ids)
TypeError: add() got multiple values for argument 'ids'
